### ISSUE TITLE
[Style] front-end/style/myscheduleDetail-page

### ISSUE THREAD

**Issue by chae-young** [preCrew/preTravel#10]
# Describtion
내 정보 상세페이지에 주요 스타일 구현

# Todo
- [x] 바텀시트에 내 일정 리스트 스타일 및 편집 기능
- [x] 상단 캘린더 버튼 , 캘린더 스타일
- [x] 상단 일차별 나오는 탭 슬라이드
- [x] 버튼, 타이틀
