### ISSUE TITLE
[Feature] front-end/feature/myschedule

### ISSUE THREAD

**Issue by Doosies** [preCrew/preTravel#18]
# Describtion
myschedule 페이지 기능 작성

# Todo
> react-query로 json-server 와 통신해서 목업 서버 데이터로 구현

- [x] #19
- 클릭시 내일정 상세 페이지로 넘어감
- 일정제목 ( 필수 )
- 시작일 ( 필수 )
- 종료일 ( 선택, 넣었을시에만 나옴)
- checkbox ( 선택, 상태 바뀌면 checkbox 나타남)
- 백그라운드 opacity 넣어야함
- 서버에서 받은 이미지 없을시 기본배경, 있을시 첫번째 배경

<br/>

- [x] #20
- MyScheduleCard를 시작일 기준으로 나열해주는 컴포넌트임
- 시작일은 서버에서 데이터를 받아올 때 정렬해줌.
  - 항목 많을경우 인피니티 스크롤 고려

<br/>

- [x] **3. IconButton 컴포넌트 생성**
- [x] 뒤로가는 버튼 ( onClick만 넣은 상태로 )
- [x] 일정 새로 추가하는 버튼 ( onClick만 넣은 상태로 )
- 나중에 검색창 페이지로 넘어가게 변경
- [x] 버튼 클릭시 일정 ( MyScheduleCard )에 체크박스 생김
- 체크박스 1개이상 선택시 삭제버튼 생김

<br/>

- [x] **4. TopBar 컴포넌트 생성**
- back 버튼은 기본 포함
- children 으로 컴포넌트 넣으면 오른쪽에 표시됨

<br/>

- [x] **5. 더미 서버 with react-query**
- 페이지 불러왔을 때 useQuery로 데이터 불러옴
- 추가버튼 눌렀을때 서버에 데이터 추가함 ( 테스트 함수만 작성 )
- 삭제버튼 눌렀을때 서버에 데이터 삭제함
