### ISSUE TITLE
[Feature] front-end/feat/schedule-plan

### ISSUE THREAD

**Issue by chae-young** [preCrew/preTravel#23]
# Describtion
일정짜기 작업

# Todo
- [x] 1.일정제목 2. 일정기간 3.사진업로드 필드 작업
- [x] 필드 작업 완료시 등록버튼 활성화( 필드 검사 )
- [x] 등록 버튼 클릭시 데이터 전송
- [x] 일정편집

**Comment by chae-young** [comment]
피그마 작업 완료
