### ISSUE TITLE
[FIX] front-end/fix/svg-issue

### ISSUE THREAD

**Issue by Doosies** [preCrew/preTravel#36]
# Describtion
1. svg를 컴포넌트로 사용하지 못하던 이슈
2. svg를 css의 background-image: url(경로) 로 사용하지 못하던 이슈

# Why?
위의 이슈가 있기에 해결하기 위해 수정

# Todo
- [x] [svgr문서](https://react-svgr.com/docs/webpack/)참고하여 webpack.config 수정
- [x] svg를 컴포넌트로 사용
- [x] svg를 url로 사용
- [x] svg를 css에서 사용
