### ISSUE TITLE
[Feature] front-end/feat/scheduleplan-api

### ISSUE THREAD

**Issue by chae-young** [preCrew/preTravel#51]
# Describtion
내 일정(스케줄 일정)추가 api 연동

# Todo
- [x] 일정 추가 쿼리 생성
- [x] 내일정 리스트 -> 지역 서치 -> 일정짜기 페이지 연동
- [x] 내일정 state 생성
