### ISSUE TITLE
[FIX] front-end/fix/230611-issue

### ISSUE THREAD

**Issue by chae-young** [preCrew/preTravel#73]
# Why?
230611 회의 후 이슈사항

# Todo
- [x]  내일정 상세에 캘린더 오류
- [x]  내일정 편집 오류 (file유무 문제! 내일정으로 일정 수정하기를 옮겨야 할것같음.)
- [x]  서브페이지에 백 기능 넣어야함
- [x]  검색 후 뜨는 맵에 맵 넣어야함
- [x]  맵 이동 기능
- [x]  내일정에서 스케줄 삭제 안됨..!
- [x]  리뷰 등록 후 메인에서 사진 연동 확인 (마이페이지 작업후 해야함)
- [x]  메인 바텀시트 오류(너무 넓게나옴. file있을경우 오류)나는 부분 수정
