### ISSUE TITLE
[FIX] front-end/fix/issues-23.06.25

### ISSUE THREAD

**Issue by Doosies** [preCrew/preTravel#75]
# Describtion
- 23.06.25 에 있었던 이슈 수정

# Todo
- [x] 쿠키에 memberIdx가 없다면 로그인 페이지로 이동
- [x] 로그인 할 때 body로 받아온 memberIdx를 쿠키에 저장해줌.
- [x] 로그아웃 할 때 cookie에 memberIdx를 삭제함
- [x] 내일정 삭제 제대로 되게 수정
